apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: guestbook-ui
 namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.teams: argocd-notifications
