name: Automatically create / update pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: environment/staging
          branch: environment/staging-next
